### ISSUE TITLE
Capybara::Server::Middleware doesn't catch RSpec::Mocks::MockExpectationError, sees blank page instead

### ISSUE THREAD

**Issue by pnc** [jnicklas/capybara#1245]
Typically, Capybara tests should run against your application without needing to mock any collaborators. However, sometimes it's necessary to mock calls to an external service (in our case, our payment processor). We use RSpec mocks to handle this.

Currently, if the mocked object receives any unexpected messages, it raises an `RSpec::Mocks::MockExpectationError`. This is the expected behavior for RSpec.

Unfortunately, the middleware that Capybara installs to catch these errors and bubble them into the test thread [doesn't catch this error](https://github.com/jnicklas/capybara/blob/master/lib/capybara/server.rb#L20). This means that if you mock an external service during a test and the mock receives an unexpected message, the server fails silently, renders a blank response, and you get a weird failure like this:

    Failures:

      1) subscribed user can upgrade their current plan
         Failure/Error: page.body.should have_text("now subscribed to")
           expected to find text "now subscribed to" in ""
         # ./spec/features/change_plan_spec.rb:73:in `block (2 levels) in <top (required)>'

rather than one like this:

    An error occurred in an after hook
      RSpec::Mocks::MockExpectationError: Double :service received unexpected message :update_subscription with …
      occurred at /Users/eleos/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-mocks-2.14.4/lib/rspec/mocks/error_generator.rb:144:in `__raise'

This appears to be because RSpec intentionally creates `MockExpectationError` such that it [won't be caught by StandardError rescues](https://github.com/rspec/rspec-mocks/blob/master/spec/rspec/mocks/mock_expectation_error_spec.rb). I assume they do this so that normal error handling in the code under test doesn't swallow these.

Would you accept a patch that made `Capybara::Server::Middleware` rescue `Exception`, or do you anticipate that causing other problems? Would it be appropriate for Capybara to just catch and bubble `RSpec::Mocks::MockExpectationError` specifically instead?

**Comment by mguterl** [comment]
This issue isn't limited to RSpec::Mocks::MockExpectationError. @mitchlloyd and I just spent hours trying to figure out why LoadError wasn't being raised in our tests.

Rescuing Exception rather than StandardError would let these errors bubble up. Currently the errors are invisible to us.

I don't think this falls under the common advice of never rescue Exception because the exception is being re-raised after being set on the middleware. It's hard to imagine an exception being raised inside of the server that you wouldn't want to see when running your tests.

We looked into providing a test case for this scenario, but we're unsure of where to write this test. capybara/spec/server_spec.rb has some coverage of the server, but it does not appear to be exercising the middleware.

**Comment by twalpole** [comment]
spec/session/reset_session_spec.rb  is where Capybara.raise_server_errors is tested and would be the place for any new tests -  Without a lot of thought on why the decision was made to only rescue StandardError originally I would be reticent to accept a change to this behavior, due to the potential of breaking tests.  We could however add something like Capybara.raise_server_all_exceptions (defaulted to false).

**Comment by twalpole** [comment]
On second thoughts we'll just make the list of errors caught configurable and default it to StandardError

**Comment by twalpole** [comment]
Would PR #1488 solve your issue(s) in the midterm - and then we can consider raising all exceptions by default in Capybara v3

**Comment by mguterl** [comment]
That will solve the problem for our use case. Thanks for such a quick turnaround!

**Comment by pnc** [comment]
@twalpole That would do it for us! I can write a section to add to the _Gotchas_ blurb in the README for your patch, if you like.

**Comment by twalpole** [comment]
@pnc - sure

**Comment by twalpole** [comment]
Merged the PR into master-  I don't foresee a new release (2.5) for at least a few weeks, so hopefully you can just use master in the meantime (after-all this has been an open/forgotten issue for over a year :) )
