### ISSUE TITLE
Capybara makes unneeded driver methods invocations when applying filters

### ISSUE THREAD

**Issue by abotalov** [jnicklas/capybara#1268]
It would be good if the following methods won't apply filters to all elements to improve performance:

1. `find` with `match: :first` option (after first matching element was found)
2. `first` (after first matching element was found)
3. `all`, `assert_selector` with `:minimum` option (after needed minimum amount of elements was found)
4. `assert_no_selector` with `maximum: n` or `count: n` option (after `n+1` method was found)

**Comment by twalpole** [comment]
Basically this would involve moving the count options logic into SelectorQuery#resolve_for.  I don't believe example 3 is actually correct, since `all` needs to return all matches even if a `minimum` option is provided - so the only optimization that  could be done for `all` would be raising an error once the `maximum` or  `count`  is exceeded. Also example 1 and 2 need to handle the case where any  count options are passed in, to make sure the overall count is correct before returning the first matched element.

**Comment by twalpole** [comment]
I've implemented something for this in PR #1734 if anyone wants to take a look/critique

**Comment by twalpole** [comment]
closed via 676fba48e2968c7d4ab7f442a8771c25a6664cb1
