### ISSUE TITLE
Field suggestions for "fill_in"

### ISSUE THREAD

**Issue by Paxa** [jnicklas/capybara#1378]
This changes save me alot of time. Because when I make mistake in field name is annoying.

```ruby
module Capybara::Node::Actions
  def fill_in(locator, options = {})
    raise "Must pass a hash containing 'with'" if not options.is_a?(Hash) or not options.has_key?(:with)
    with = options.delete(:with)
    find(:fillable_field, locator, options).set(with)
  rescue Capybara::ElementNotFound => exception
    all_fields = [];
    all(:fillable_field).each do |el|
      all_fields << el[:id] || el[:name]
      if el[:id].present?
        label_selector = %{label[for=#{el[:id]}]}
        if has_css?(label_selector)
          label = find(label_selector)
          all_fields << label.text
        end
      end
    end
    raise Capybara::ElementNotFound.new(%{Unable to find field "#{locator}", did you mean one if this: #{all_fields}})
  end
end
```

```
Unable to find field "Transaction fee1", did you mean one if this: ["Transaction fee", ...]
```

I think it would be nice to have it in capybara, what do you think?

**Comment by chrisccerami** [comment]
Has anything like this been implemented yet? I think it sounds useful and I'd be interested in implementing a solution like this. Perhaps something similar for all ElementNotFound exceptions where it would recommend any elements with similar names. I can't count the number of times a field like "Title" hasn't been found because I was searching for "Title:" instead or something similar.

**Comment by Paxa** [comment]
You can use this monkey patch. It works for me

How you want to detect possibilities for every ElementNotFound?
If I do `find('.page_title')` I don't know how to make it, list all possible css selectors will give too much information.

**Comment by twalpole** [comment]
The problem I have with this is that the locator can be id, name, or label text - so printing out only some of those is incomplete and can lead to more confusion, yet printing everything could lead to huge strings of text on some pages.  This also misses the label text for labels with nested inputs and no 'for' attribute

**Comment by Paxa** [comment]
So you suggest to use only one selector? last?

```ruby
find('section div.some-class') # => suggest for other classes?
```

I just had other problem now: hidden elements, I think need to make suggestion for that too

**Comment by twalpole** [comment]
@Paxa This should not be done for #find - It is impossible to determine what the user may have wanted there.  I was referring to your initial code, which only outputs id or name and some label text, it ignores name (if an id exists),  placeholder, and some labels text in its suggestion list.  I think an incomplete suggestion list is actually worse than no suggestion list since it creates the illusion of having all the info when in fact you don't.

**Comment by chrisccerami** [comment]
So are you thinking you wouldn't want to see something like this implemented at all? Or would you be willing to consider some sort of implementation for adding the extra output to the ElementNotFound exception? I was thinking about trying to work on an implementation when I get some free time this weekend, but if it's something you aren't interested in at all, I won't bother with the PR.

**Comment by twalpole** [comment]
@chrisccerami your description of doing it for all ElementNotFound errors is basically impossible,  those errors can come from any valid CSS or XPath selector, and trying to determine the users intention for that isn't really doable

**Comment by Paxa** [comment]
@twalpole I think if we make it for `find` it will give wrong suggestions. For example fill_in, select, click_link etc using find inside. I think better to make decorators for errors every case. And may be make special case to detect if `find` called from capybara or from user's test

**Comment by Paxa** [comment]
I have one more thing: (looks ugly but it works)

```ruby
module Capybara::Node::Actions
  def select(value, options = {})
    orig_options = options.dup

    if options.has_key?(:from)
      from = options.delete(:from)
      find(:select, from, options).find(:option, value, options).select_option
    else
      find(:option, value, options).select_option
    end

  rescue Capybara::ElementNotFound => exception

    # Lets transfor 'Unable to find option "X"' to more helpful message
    if exception.message =~ /Unable to find option/
      if orig_options.has_key?(:from)
        options = find(:select, from, options).all('option')
        options_titles = options.map(&:text)
        #p options_titles
        raise Capybara::ElementNotFound, "#{exception.message}, options: #{options_titles}"
      else
        raise exception
      end
    else
      raise exception
    end
  end
end
```

before:

```
Capybara::ElementNotFound:
       Unable to find option "Cancel1"
```

after:

```
Capybara::ElementNotFound:
       Unable to find option "Cancel1", options: ["Process", "Cancel"]
```

**Comment by twalpole** [comment]
@pavel - The "if we make it for find it will give wrong suggestions" is exactly my point about not being able to do it for all ElementNotFound errors.  Doing it for all the methods in actions.rb is probably possible.

The issues I have with your other two suggestions are 
1. Your #fill_in method is incomplete in the suggestions it offers (as detailed in a previous message)
2. Both of these methods have a race condition where it's possible to get an error like
   Unable to find field "Title" did you mean one of these ["Title", ....]  
   Where it's telling you it couldn't find a field and then asking if you meant that exact same field.  This is because of the time delay between the field not being found and then getting all the available things on the page.   I don't think there's really a clean way to fix that possibility so it should probably be checked for when the error message is generated and make a statement about the race condition if it happens.  This may have to take into the match mode currently being used.
3.  This behavior would need to be turned on/off with a setting  -  Capybara.suggest_on_action_failure  or something like that

**Comment by twalpole** [comment]
Closing due to age, and the nebulous chance of this even being doable in a complete manner than is useful
