### ISSUE TITLE
Method "visit" adds /content/index-m.php at the end of my URL

### ISSUE THREAD

**Issue by toshidavila** [jnicklas/capybara#1469]
It happens from time to time when I run cucumber.

It randomly adds /content/index-m.php at the end of my URL which makes the scenario fail because the page is never loaded because that specific url doesn't exist.

I must say I am new with cucumber & capybara. This is how my steps.rb file looks like: 
```
#BACKGROUND:
Given (/^I am on login page$/) do
  visit $page
end
```
where `$page` stores my website page.

And this is how my env.rb file looks like:
```
require "Capybara"
require "Capybara/cucumber"
require "rspec"
Capybara.default_driver = :selenium
```

![capybara_visit](https://cloud.githubusercontent.com/assets/3664943/5858546/00459214-a222-11e4-8f46-53103d959425.jpg)

**Comment by twalpole** [comment]
Since the string /content/index-m.php is nowhere in capybara, this is not a capybara issue -- I would check the value of the $page variable before you call visit and if its correct there then your code is probably redirecting.  In the future, if you are not 99.9% sure its an issue with Capybara, please ask questions on the mailing list as requested in the README

**Comment by toshidavila** [comment]
Hi,

the $page variable is https://www.mypage.com and it happens randomly with the method visit...
