### ISSUE TITLE
In README, clarify which finder methods honor default_wait_time.

### ISSUE THREAD

**Issue by bbuchalter** [jnicklas/capybara#1481]
Hope this is the right forum to ask this question. While reviewing https://github.com/jnicklas/capybara#asynchronous-javascript-ajax-and-friends it wasn't 100% clear about which finder methods are AJAX-friendly. In the [documentation](http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Finders:find) *only* `find` is said to honor `default_wait_time`. Do any others? If not, it would probably be best to make this explicit in the README. I'd be happy to submit revision based on your guidance. Thank you!

**Comment by bbuchalter** [comment]
Additionally, it would be nice to be explicit about which RSpec matchers support `default_wait_time` as well.

**Comment by philipfong** [comment]
I would be curious to know which finders and matchers *do not* support the default_wait_time.  In my experience, I've not seen many specs get ahead of itself and fail before the default_wait_time.

**Comment by twalpole** [comment]
All the finders are implemented via either #find or #all which both support waiting through either default_wait_time or a :wait option passed to the finder, so all the capybara provided finders support waiting.  For #all to wait one of the count options would need to be passed to it (otherwise 0 matching elements is a valid return).  PRs updating the documentation would be welcome

**Comment by twalpole** [comment]
Just realized I didn't mention the matchers -- they all support waiting as well

**Comment by philipfong** [comment]
Can someone help with this scenario?  This type of rspec matcher does not wait, and will fail immediately.  Please note that I'm still using the old 'should' syntax.

page.all('foo').size.should == 3

This type of statement doesn't appear to "wait" for the result to become 3.  I have to wrap this line with some code to mimic the default_wait_time being used.

**Comment by abotalov** [comment]
@philipfong In that statement a matcher is `==`. This matcher is provided by RSpec, not Capybara and doesn't wait.

**Comment by twalpole** [comment]
@philipfong  Also note that as I stated above regarding capybaras finder - "For #all to wait one of the count options would need to be passed"  - so you could also do 

    page.all('foo', count: 3).size.should == 3  

Obviously that doesn't read all that well, and the first example provide by @abotalov is probably the cleanest reading way to do what you are doing - with 'should' syntax it would be 

    page.should have_css('foo', count: 3)

**Comment by philipfong** [comment]
I just tried out the capybara finder with the count option and it works beautifully!  I did not know that option was supported.  Thank you, @twalpole @abotalov

**Comment by twalpole** [comment]
@philipfong http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Finders#all-instance_method   -- you can also specify minimum, maximum, between

**Comment by mcmire** [comment]
Oh wow. I was under the impression that #find waited but #all did not wait. I see now that this is not quite the case.

Specifically, both #find and #all run a query to find the element(s) in question. Capybara will run this query again if it detects a Capybara::ElementNotFoundError, or an "invalid element error" -- this will come from the driver, so for instance Selenium will raise a Selenium::StaleElementReferenceError. It will run the query over and over until `Capybara.default_wait_time` is reached.

Why does it seem that #find waits but #all does not? Because #find will raise a Capybara::ElementNotFoundError by default if it cannot find the element in question, and #all will *not*. In other words #all still waits, but it fails a lot faster. 

In response to

> For #all to wait one of the count options would need to be passed

It looks like judging from the [code](https://github.com/jnicklas/capybara/blob/master/lib/capybara/node/finders.rb#L152) that passing options to #all does modify the query that Capybara will run, but it doesn't necessarily cause it to wait. Specifically, if you provide `:count` Capybara will raise Capybara::ExpectationNotMet immediately if the number of elements found doesn't match your `:count` (and will not retry the query).

**Comment by mcmire** [comment]
So to answer the OP, saying that #find is the only method that supports `Capybara.default_wait_time` isn't quite correct. Both #find and #all support `Capybara.default_wait_time`, but #find is more aggressive at attempting to find the element in question; #all will simply fail if it can't find those elements (even with `:count`).

**Comment by twalpole** [comment]
@mcmire You missed the fact that the ExpectationNotMet error is derived from ElementNotFound, so it will actually trigger a retry.   Using any of the count type options (count, minimum, maximum, between) will cause all to wait up the passed in wait time (or default_wait_time) for a set of elements that fulfill the requirements

**Comment by mcmire** [comment]
@twalpole Ahh... nice, well, I stand corrected. That's very cool.

So yeah... the docs should definitely be updated in this case.

**Comment by bbuchalter** [comment]
Well done @twalpole thank you!
