### ISSUE TITLE
Consider modifying Node#first to raise an error instead of returning nil if there are no elements

### ISSUE THREAD

**Issue by abotalov** [jnicklas/capybara#1507]
See https://github.com/jnicklas/capybara/pull/1506

The thing is, Node#first returns `nil` only if no elements matched passed args. We have `assert_no_selector`, etc. for this use case.

**Comment by twalpole** [comment]
My only real concern with this is if people are using first to check for presence on a page and changing behavior based on that

    if link = page.first('a')
      do something with the link.....
    else
      other behavior...
    end

What would be our recommended way of doing something like that if #first raised instead of returning nil?

**Comment by RSO** [comment]
@twalpole before #1506 that example was unsafe, as it wouldn't wait (it still is unsafe by default), right?

Would it be doable to recommend using `page.has_no_selector` for this scenario?

**Comment by twalpole** [comment]
@RSO Waiting doesn't make anything safe or unsafe, it just determines the time period during which an elements is looked for on the page.  If I know the page is not dynamic in anyway and just need different behavior depending on whether or not a certain item is on that page then the above is a perfectly valid (and "safe") way to make that determination without having to do two finds on the page.  Using has_selector? or has_no_selector? followed by another find to get the actual element just results in a slower test.

**Comment by RSO** [comment]
Yeah, I think I get your case. What I meant with "safe" (and what I think you get, but just wanted to make sure) is the fact that it's error-prone, even for non-dynamic pages. E.g:

```ruby
visit '/page'
if link = page.first('a')
  # probably not gonna happen
else
  # page still loading, or really not there
end
```

But, I think that you're looking for a way to make the non-waiting call anyway, correct? Isn't this some kind of pattern that applies to other ways of selecting throughout Capybara? Like, isn't there something like `first('a', wait: false)`?

**Comment by twalpole** [comment]
The use case I specified would be more for use in test helper functions where it may need to handle two different things - without the user caring which.  This issue isn't about the waiting or not, its about whether or not I can use #first to determine behavior.  If it raises I cannot, if it returns nil when no matching element is found it can, and has been in returning nil vs raising an exception.  So say I have a message box that appears on screen and I want to be able to close it - sometimes there's a checkbox that needs to be checked, othertimes there's not.  In most of my tests I don't really care whether the checkbox is there or not just that when it is there it gets checked.  I know that when the box appears the checkbox will already be there if it is going to be there, so while I may need to wait while finding the box, I don't need to wait while checking for the existence of the box

    def close_box
       box = page.find('.box')
       if cb=box.first('some selector or other', wait: 0)
         cb.set(true)
       end
       box.click_link('Close')  
    end

If first raises rather than returning nil I could write the relevant part of that as 

    if box.has_selector?('some selector or other', wait: false)
      box.first('some selector or other').set(true
    end

but that has duplication of the selector and a second search for the element for no particular reason. I could also write it as

    begin
      box.first('some selector or other').set(true)
    rescue Capybara::ElementNotFound
    end
 
That's not exactly elegant but at least it only  does one search for the matching element.

As for your definition of "safe" - we've been through this a couple of times with Capybara, and it comes down to the developer having to know what they're expecting their page to be doing, when they need to wait and when they don't.  There are a number of methods that can negatively affect test times if a developer doesn't understand what they are testing for and which method to use for that test.  There really isn't a way for Capybara to make sure everyone does the "correct" thing and still allow flexibility to do what is needed.  See issue 1435.   

Anyway that's getting off topic for this issue.

**Comment by twalpole** [comment]
Implemented via 7cffbb36f82cd58e3e7ed6c9bd9880d08f0d2c5e in 3.0_dev branch

**Comment by tobico** [comment]
Hey, this change broke my test suite. I was relying on this behavior to implement code that branches based on whether or not a certain element is on the page. What would be the correct way to do this now that this change has been implemented?

**Comment by twalpole** [comment]
@tobico See https://github.com/teamcapybara/capybara/blob/master/UPGRADING.md - also if you're only making a decision based on element existence and not actually using the element you should be using the predicate methods `has_css?`/`has_xpath?`/`has_selector?` etc. rather than `first`
