### ISSUE TITLE
select with value very slow to enumerate.

### ISSUE THREAD

**Issue by bebepeng** [jnicklas/capybara#1527]
When I have a `<select>` element on my page (and it has a label 'Country'), and I select an option by value:
```
  $('#my_select').value = 'US'
```
Capybara takes over 20 seconds to assert that this is selected using:
```
  expect(page).to have_select('Country', selected: 'US')
```

I narrowed it down to the line https://github.com/jnicklas/capybara/blob/master/lib/capybara/query.rb#L118 where the query was './/option' 

If i put 'selected' on the option, Capy is fast, but when using DOM API, it's slow.

Any help you can provide will be appreciated.

Regards,
  [Rasheed Abdul-Aziz](https://github.com/squeedee)  && Bebe Peng

**Comment by bebepeng** [comment]
@squeedee

**Comment by twalpole** [comment]
If you can provide an example that reproduces we will look into it, otherwise I don't see how this is possible, unless maybe your page is ridiculously large. have_select will time out in 5 seconds (by default), so there is no way it should be taking 20 seconds

**Comment by bebepeng** [comment]
We will try to produce an easily reproducible example. The timeout is not hit because the time taken by Capybara::Result.new does not relinquish control to synchronize. When it's done, it matches, so no exception, so the test passes (despite being 20 seconds after the start of the match). 

The page is not ridiculously large, the query is contextualized to the select that matches in the outer query (outer query is where it finds the select via its `label` element). The number of options is not large, so the xpath query is fast. The result from the xpath query has approx. 250 option nodes, which are passed to `Result.new`, where things come to a crawl. That's as far as we investigated. Will work on a sample for you.

**Comment by twalpole** [comment]
What driver are you using? and if selenium, which version?  (2.45 has a serious performance bug in it which can cause major test slowdowns - unfortunately 2.46 has not been released).  So having 250 option nodes, each of which has to be queried for whether or not it's selected could take some time, but it really shouldn't be 20 seconds, although with the 2.45 performance issue in selenium maybe it would.  Unfortunately we can't change the query to  './/option[@selected]' since xpath only queries against the attributes in the document, not the properties - this means that if a selection is changed after the document is loaded the results of the xpath query would not be correct.  Technically it could be possible to swap to a css query of  'option:checked' which would be evaluated against properties but that then brings up browser support issues.

**Comment by bebepeng** [comment]
We are using selenium-webdriver 2.45.... :( We'll see if selenium edge makes a difference.

**Comment by twalpole** [comment]
FYI - the releveant selenium issues are 

https://code.google.com/p/selenium/issues/detail?id=8551
https://github.com/SeleniumHQ/selenium/issues/383

**Comment by twalpole** [comment]
selenium-webdriver 2.46.1 has been released --  please let me know if that improves your situation

**Comment by bebepeng** [comment]
Yeah the new release for selenium totally helped! We're down to 6 secs. Thanks so much for your help. :)

**Comment by twalpole** [comment]
@bebeng Would it be possible for you to run it using the selected_optimization branch and see what the time is then please?

**Comment by bebepeng** [comment]
Here are all the combos tried again:

Selected_optimization + Selenium 2.45.0 = ~5.5 secs
Selected_optimization + Selenium 2.46.1 = ~4 sec
Capybara 2.4.4 + Selenium 2.45.0 = ~23 sec
Capybara 2.4.4 + Selenium 2.46.1 = ~7 sec

**Comment by twalpole** [comment]
So the optimization saves about 25% with the non-broken selenium on selects with a large number of options, not sure it's worth it for the added code complexity.  Will have to think about it. 
Thanks
