### ISSUE TITLE
have_content and have_text show confusing messages for given keys

### ISSUE THREAD

**Issue by ndnenkov** [jnicklas/capybara#1549]
Using version (2.4.4)
```ruby
require 'capybara/rspec'

Capybara.default_driver = :selenium

describe "Github", :type => :feature do
  it "has welcoming page" do
    visit 'https://github.com/'
    expect(page).to have_content 'Build software better, together.', exact: true
  end
end
```

Will succeed and show a confusing message:
> invalid keys **:exact**, should be one of :text, :visible, :between, :count, :maximum, :minimum, **:exact**, :match, :wait

This will also happen for other invalid keys.

**Comment by twalpole** [comment]
The message is confusing and will be fixed in the 2.5 release, however the gist of the message that :exact is an invalid option for have_content/have_text is correct.  If you really want to match the text exactly (rather than just look for the passed string to be a substring of the page/element content) then you should pass a regex  /\ABuild software better, together\.\Z/
