### ISSUE TITLE
Capybara not compatible with Chrome latest version

### ISSUE THREAD

**Issue by jessicadanaowens** [jnicklas/capybara#1553]
After updating Chrome to version 44, some capybara started to break, specifically tests where a user logs in.  However, not all of the tests that have a logged in user failed.  Oddly, I fixed the failing tests by inserting a sleep .1 right after the code that signs the user in.  I also fixed the tests by using Chrome version 43.  I have no idea how to make my tests compatible with Chrome version 44 without adding those inexplicable sleeps.

**Comment by twalpole** [comment]
Chrome 44 has a number of issues with chromedriver -  the 2 biggest being

https://code.google.com/p/chromedriver/issues/detail?id=1158&colspec=ID%20Status%20Pri%20Owner%20Summary

https://code.google.com/p/chromedriver/issues/detail?id=1159&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary

For the second issue of special keys not working theres not Capybara can do to fix, so hopefully Chrome or chromedriver will make a change to make that work again.

For the first issue, the problem is that a lot of actions now return much sooner than they used to (visit returns before the new page has started loading, etc) - and the proper solution to that is really having your tests wait for content from the new page (rather than just sleeping 0.1 seconds) before performing other actions, so that Capybaras implicit waits allow for the browser to catch up.  The other option may be do something like  

  expect(page).to have_no_css('#login') 

in the end of your login method, to have the test wait for the page to unload.  Either way this isn't really an issue on Capybaras side, just a massive change in behavior of chromedriver that may require a bunch of work to make tests compatible - hopefully they revert the behavior
