### ISSUE TITLE
has_content returns true for nil

### ISSUE THREAD

**Issue by sharmarahul** [jnicklas/capybara#1573]
I am trying to assert if text for a given node matches value returned from an API but when API returns nil for a value, it still passes.

    expect(#node_id).to have_content API.value

if the API.value is nil the test still passes. Should text eq be used here?

**Comment by twalpole** [comment]
This is as designed, have_content verifies the page/element contains the passed string at least once (or more if any of the count options are passed) - if you want to check for an exact match you need to pass a regex to have_content

**Comment by sarojkh** [comment]
Just adding in this comment here so future visitors digging this issue can find this easily using search term "have_text".

**Comment by sarojkh** [comment]
@twalpole 

To reiterate the original description of the issue, the following passes.
```
expect(page).to have_text nil
```

Isn't this bound to create a lot of false positives? Lately, I have come across a lot of false positives in test suite of one of the projects I am working on.

In contrast to what you have mentioned in the comment above, I think passing of `nil` as the expected text should not be allowed. 

Having said that, you obviously know better. Also, big thanks for maintaining this project.

**Comment by twalpole** [comment]
@sarojkh It depends what you mean by false positives.   `have_text` takes a string and checks whether the text in the element contains that string.  Since nil.to_s returns "" it's the same as `have_text ""` which every string contains. So if someone assumed that passing `nil` would check the element was empty, without reading the docs, then that user might consider it a false positive, but really it's just a failure to read the docs. if the you want to check the text is empty then you probably want to be doing an exact match

    expect(element).to have_text nil, exact: true

**Comment by twalpole** [comment]
Thinking about this a bit more -- have_text is documented to take a string or regexp so outputting a warning on `nil` as being confusing may not be a terrible idea.
