### ISSUE TITLE
Driver for String

### ISSUE THREAD

**Issue by samstickland** [jnicklas/capybara#1576]
Hi,

How much work do you think it would be to have a very basic driver for HTML strings using webkit or selenium?

I know I can already use the Node matchers on strings, but I'd like to be able to save a rendered screenshot in order to help debug our View and Cell specs.

I'm happy to look into this myself, but I'd like it if someone with knowledge of the capybara internals could give me a steer on whether it's possible/practical and how much work this would be.

**Comment by twalpole** [comment]
To save a rendered screenshot of a string - you would need to load the string into webkit or selenium so they can process and render the css.  If you know its a static html string without any JS or anything you could save it to a file and then open that file in FF or whatever.  However,  wouldn't it just be easier to set up your tests to rerun failing tests in selenium or webkit and save a screenshot from there.  

I'm closing this since its not an issue with Capybara, if you want to discuss further please move over to the mailing list detailed in the README
