### ISSUE TITLE
have_select with filters does not respect :visible option

### ISSUE THREAD

**Issue by naw** [jnicklas/capybara#1579]
`page.have_select('Label', visible: false, selected: 'selected option')`

The select will be found (even though it is hidden), but the selected option will not be found because it (and its text) are hidden.

I would have expected the filter to match even if the option is hidden (if `visible: false` is specified).

Fixing it seems like it would require a change to the filter system in general.

 As far as I can tell, the filter system itself does not pass the underlying options hash (containing `visible: false`) to the filters when checking for a match, so there is no way for the filter to make determinations based on `visible: false`.

Questions:

1. Would you agree that the filter _should_ match on a hidden option, provided `visible: false` is 
specified?
2. Would you be open to a PR to fix this?
3. Passing the underlying options hash to `Filter#matches?` seems like one viable solution, although perhaps heavy-handed.  Any alternative suggestions?

**Comment by twalpole** [comment]
I think the selected filter should not care about the visibility status of the options at all --- if they're selected they should be matched

**Comment by naw** [comment]
In that case, the fix is easy:

https://github.com/naw/capybara/commit/e855c2d5da38bad2ae94ebc9860112c745a9ecf1

What do you think about visibility in the other filters, such as `options` and `with_options`?

**Comment by twalpole** [comment]
options and with_options are slightly more complicated - if the select isn't visible (which can be checked from the node element) then there's no point checking the visibility of the options since they can't be visible so they should probably all be considered.   If the select is visible (which can again be checked from the node) then we obviously want visible options, but do we want hidden options.  I would guess no - and if if the user really wants to check for a visible select with non-visible options then they may have to resort to querying the options individually
