### ISSUE TITLE
:xpath assumtion

### ISSUE THREAD

**Issue by Nakilon** [jnicklas/capybara#1588]
The default finding method is by_css. I would love if it was by_xpath if selector begins with "//" (and maybe ".//") because I use xpath in 30-50% of selectors.

**Comment by twalpole** [comment]
Capybara isn't going to start trying to detect the type of selectors by default because that just ends up  opening a can of worms.  However, if you want to add the behavior for your project it's easy enough to replace the current :xpath selector with one with a match proc that will make your wanted behavior happen.  Executing something like the following code after Capybara has loaded its builtin selectors will replace the existing :xpath selector and make find default to :xpath if a selector type is not passed but the locator starts with .//   


    Capybara.add_selector(:xpath) do
      xpath { |xpath| xpath }
      match { |locator| locator.start_with?('.//') }
    end
