### ISSUE TITLE
rack_test driver returns unescaped current url which may cause issues with have_current_path

### ISSUE THREAD

**Issue by lukerollans** [jnicklas/capybara#1611]
I intend to open a PR to address this issue, just don't have the time right this minute :)

When using `have_current_path` to match the request path and query string, it does not work with non alpha numeric characters, most importantly for checkbox arrays

In my case, when searching "Location" objects by an array of categories passed in via a checkbox array

```ruby
expect(page).to have_current_path search_locations_path(categories: ["awesome-things"])
```

produces this

```
  1) Location searching allows the user to select from a list of categories
     Failure/Error: expect(page).to have_current_path search_locations_path(categories: ["awesome-things"])
       expected "/locations/search?categories[]=awesome-things" to equal "/locations/search?categories%5B%5D=awesome-things"
```

To address this bug, I imagine the expected string should be uri encoded.

Thoughts?

**Comment by twalpole** [comment]
what driver are you seeing this with?

**Comment by lukerollans** [comment]
It's not a JS spec, so whichever driver is default. Do you still think it may be a driver issue?

**Comment by twalpole** [comment]
The default driver is racktest, and I'm 95% sure this is going to be a driver specific thing.  The have_current_path matcher works by calling URI.parse on what the driver returns for current_url and then using the relevant parts.

**Comment by twalpole** [comment]
So this is because the racktest driver returns unescaped urls for current_url even when the url visited was escaped.  As a workaround short term you could call URI.unescape on the path you're passing to have_current_path....   I need to find time to look into the rack_test driver and figure out why it's doing that, or maybe just update have_current_path to compare against the url as passed in and an unescaped  version of it - need to think about it
