### ISSUE TITLE
Element not found on page when opacity is 0 and visible set to false

### ISSUE THREAD

**Issue by kleinab** [jnicklas/capybara#1620]
I know that I can use the workaround Capybara.ignore_hidden_elements = false, but it seems to me that the visible flag set to false should account for opacity 0 objects on the page.

**Comment by twalpole** [comment]
Please provide an example that shows this issue

**Comment by kleinab** [comment]
Example:

HTML:
```html
<div class='foo' style='opacity: 0;'>Hello world</div>
<div class='bar' style='display: none;'>Hello world</div>
```
Ruby:
```ruby
@session.find('.foo', visible: false).text # returns ""
@session.find('.bar', visible: false).text # returns "Hello world"
```
Shouldn't the foo line also return "Hello world"?  Or is there another solution?

**Comment by twalpole** [comment]
ok, so neither of those raises an "element not found" so the title of this issue is incorrect.  #text takes a parameter of whether or not to return invisible text as documented here - https://github.com/jnicklas/capybara/blob/1a9417061c08194d9c4332cbbac186798cd5978a/lib/capybara/node/element.rb#L55 .  Because of this your .bar example should also return an empty string as written, what driver are you using?

**Comment by kleinab** [comment]
Ok

**Comment by kleinab** [comment]
Thanks for your help>
