### ISSUE TITLE
assert_selector and assert_no_selector - bad performance due to unnecessary exceptions

### ISSUE THREAD

**Issue by Kache** [jnicklas/capybara#1621]
`Capybara::Node::Matchers#assert_selector` and its negation, `assert_no_selector` are boolean and are expected to only return `true` or `false`.

However, in the case of `false`, rather than just returning `false`, they are implemented with an unnecessary `raise` & `rescue` `return false`, resulting in extremely bad performance, i.e.. (pseudocode):

    def has_selector
      assert_selector
    rescue Capybara::ExpectationNotMet
      return false
    end

    def assert_selector
      assertion_holds = #compute
      if !assertion_holds
        raise Capybara::ExpectationNotMet
      end
      return true
    end

Example use case is when branching logic based on the existence of an element on the page:

    if session.has_css?("div#may_or_may_not_exist")
      # no problem
    else
      # unnecessarily slow if not found
    end

Current workaround is to provide a `:count` option:

    !session.has_css?("div#may_or_may_not_exist", :count => 0) # no performance hit

Anecdotal benchmarks:

    2.2.1 :092 >   n = 10
     => 10
    2.2.1 :093 > Benchmark.bm do |b|
    2.2.1 :094 >       b.report("!has") do
    2.2.1 :095 >           n.times { !session.has_css?("asdf") }
    2.2.1 :096?>       end
    2.2.1 :097?>
    2.2.1 :098 >       b.report("has no") do
    2.2.1 :099 >           n.times { session.has_no_css?("asdf") }
    2.2.1 :100?>       end
    2.2.1 :101?>   end
           user     system      total        real
    !has  0.400000   0.100000   0.500000 ( 20.395774)
    has no  0.010000   0.000000   0.010000 (  0.052803)

P.S.

The same is true for `Capybara::Node::DocumentMatchers` as well.

**Comment by twalpole** [comment]
You don't understand what you're actually testing here - it has nothing to do with exceptions and everything to do with Capybaras waiting behavior - if that's not enough explanation I'll add more details tomorrow when I have time

**Comment by Kache** [comment]
It sounds like you're referring to the `Capybara::Node::Base#synchronize` wait/retry behavior.

I picked up Capybara for use as a common Ruby API for automating both PhantomJS and Chrome, and I did not expect `has_css` to wrap a test/assertion framework. I suppose since Capybara is _intended_ to be a testing framework, `has_css` is synonymous with "`assert_has_css`".

It wouldn't be out of the question for me to feature-request for a non-test framework configuration that loads a different implementation of the various `Matchers`, would it?

**Comment by twalpole** [comment]
Correct, this has to do with the #synchronize wait/retry behavior

When you call has_css?  the code will check for the existence of matching elements, if elements exist it will return true immediately, if they don't it will continue checking for up to Capybara.default_max_wait_time seconds for the element to appear.  If after that time matching element(s) have not appeared it will return false.  When using has_no_css? this behaves in the opposite manner, will return true immediately if no matching elements exist, otherwise it will wait for matching elements to disappear from the page, or return false once the maximum time has passed.  The reason for this behavior is if you have code like the following

    click_link 'new_page'
    if page.has_css?('div.intro')
      .... # do something
    else
      .... #do something else

the click_link executes asynchronously, so the new page may not be loaded when the call to has
css? starts.  The waiting behavior ensures the page has time to load and check for the div.intro element to appear.  If you know for sure the page is loaded when you want to make the decision you can always pass wait: 0 to the has_xxx? method and it will disable the waiting behavior, like below

    click_link 'new_page'
    expect(page).to have_text('You are on the new page')
    if page.has_css?('div.intro', wait: 0)
      ... # do something
    else
      ...  # do something else

In this case - the waiting for the page to load is done by the have_text expectation waiting for something that appears on the new page but wasn't on the previous page.  Since we know the page is loaded we can then disable waiting in the call to has_css? by passing a wait time of 0 seconds
