### ISSUE TITLE
click_button clicks wrong button

### ISSUE THREAD

**Issue by andersennl** [jnicklas/capybara#1627]
Hi, I've got the following part of a form:
```erb
<div class="user-form-controls">
  <%= link_to "Back", :back %>
  <%= f.submit "Update account", id: "update-button" %>
</div>
<% end %> <!-- form end -->

<h3>Delete Account?</h3>

<%= button_to "Delete my account", registration_path(resource_name), :data => { :confirm => "some validation message." }, :method => :delete %>
```

In my `spec`, I try to click the `Update account` button using capybara:
```ruby
# with or without the within block
within(".user-form-controls") do
  click_button "update-button"
  # or
  click_button "Update Account
end
```
It's always the `Delete my account` button which is being clicked (+ the validation is automatically confirmed). No matter how I try to target the `Update account` button, it's always the wrong one being triggered and so my test obviously fails. 

If I remove the `Delete my account` button from the template, the correct, `Update account` button, is being triggered. 

I'm not sure if I'm doing something wrong or this is a bug? Thanks a lot!

Update:
Interestingly I didn't think about this solution as this has like always worked (not sure what broke it) but changing the `button_to` to a `link_to` seems like to solve the problem.

**Comment by twalpole** [comment]
What driver are you using?

**Comment by andersennl** [comment]
I didn't set any driver so I guess I'm using `:rack_test`.

**Comment by twalpole** [comment]
Ok, so the rack_test driver doesn't support any JS or most CSS.  Because of this there would be no confirmation since its JS driven.  Without seeing the rest of your form, I'm going to assume it also has JS dependent behavior and what you're actually seeing is the results of clicking the correct in a non-JS supporting browser. You can test that by disabling JS in your browser or just looking at what's actually submitted in your logs. The odds of the rack_test driver having an issue with clicking the wrong button are very low.
