### ISSUE TITLE
Unable to find or open a Foundation 5 modal in Capybara with Selenium-webkit driver

### ISSUE THREAD

**Issue by bytenel** [jnicklas/capybara#1631]
Hi there!

I posted a question on the popular Q&A site StackOverflow the other day (http://stackoverflow.com/questions/34500357/capybara-with-selenium-not-rendering-partial) but the more I think about it the more I am starting to be convinced that the problem is laying in the Capybara gem itself or possibly in the seleinum-webkit driver. I have a Foundation 5 modal window that is hidden by default and after a click on a link there should be a reveal that allows the user to interact with that modal. It does not appear to be rendered at all in the Firefox window that loads but it is present when I call save_and_open_page in the test. The rails_helper I have for the project is listed in the above link. Let me know if you need anything else! Been a very frustrating issue to deal with to say the least.

One of the most telling thoughts I have about the issue is that I have the line:
```
 within("div#line_item_#{@first_line_item_id}") do
      find('#split-transaction-icon').click
 end
```

Which should reveal the modal window in the Firefox. It doesn't though, nothing loads which is strange. The icon also doesn't display (it's a SVG icon that is rendered using CSS) which is really strange but we don't get a  Selenium::WebDriver::Error::ElementNotVisibleError when trying to interact with it so I'm not sure what the problem is.

**Comment by twalpole** [comment]
Without a reproducible example we can interact with there is no way to debug this.  If you can provide a simple reproducible example that shows the issue, and/or a way for us to interact with it then we can potentially look at it.  Without that, all we can really say is there are thousands of people a day click on links that have JS actions that make modals appear and it works for them, so the issue is more likely to be with your test code and or app than with Capybara.  If you can provide a reproducible example we will reopen this.
