### ISSUE TITLE
Slow Capybara::Server boot blocking in #responsive? method

### ISSUE THREAD

**Issue by tjouan** [jnicklas/capybara#1636]
I experience slow (some minutes) boot time of the server when using a
javascript driver. I saw it was blocking during `connect` but that no
server was running at this time, the server is only started after a
first connection failure. I have been using the following quick
workaround as monkey patch since months:
https://gist.github.com/anonymous/9b160239c098aefb266f, which prevent
doing the first connection attempt (the one before server start) and
it worked well for me.

I wanted to work on a proper fix (by the way I could not find the
mailing list address, sorry for opening an issue directly), but I face
multiple problems: I can't run the test suite easily on master as it
can takes hours to complete, it fails on unrelated specs (I would need
a custom WM as I understand:
https://github.com/jnicklas/capybara/blob/master/.travis.yml#L49-L51),
my "fix" breaks existing specs on `Capybara::Server`, and seems to
have side effect on the test suite (`Errno::EADDRINUSE` errors during
`bind`).

I'm very unfamiliar with ruby `Thread` API and don't have rubinius
anymore so this is as far as I could go:
https://github.com/tjouan/capybara/compare/fix-server_responsive-thread_check.

* tjouan/capybara@c3038fb "fixes" the last server spec, I think the
  intent was originally to stub the HTTP connection, not to add an
  expectation;
* tjouan/capybara@c26bcec is to allow increasing server wait time, it
  was not enough in my case, first connect is always longer than the
  hard-coded 60 seconds;
* tjouan/capybara@b99fbf2 adds a guard clause to `#responsive?` so it
  returns early and details what may be an issue as I understand it:

        `Server#boot' calls `#responsive?' before starting the server, which
      will make the program block on a connection attempt to the host and port
      where the server should be running.

        After some time, the `connect' system call returns with an error,
      `#responsive?' returns false and `#boot' execution resumes. The server
      is then started, `#responsive?' is called again and a new connection
      attempt is made.

        This change add an expression in the guard clause for `#responsive?'
      method to explicitly test that @server_thread is falsy, and return false
      in that case.

Here are the errors on Travis CI:
https://travis-ci.org/tjouan/capybara/builds/102936275

The one for MRI seems random, but the one for rbx-2 seems consistent.

**Comment by twalpole** [comment]
The "mailing list" is linked to right from the top of the README
* Need help? Ask on the mailing list (please do not open an issue on GitHub): http://groups.google.com/group/ruby-capybara"

The monkey patch you have been using breaks the use of Capybara with multiple sessions, and is why you have test failures after applying it.  Capybara will sshare one server thread amongst multiple sessions that use the same application instance to reduce memory usage, etc.  Because of this the session first attempts to connect to an existing server instance (that may exist in another session - the first responsive? call) and if that connection is refused it then starts up a new server thread and waits (up to 60 seconds) until that is responsive.   
  If you're having an issue where the first responsive? call takes a long time to be refused you really need to look at your system/firewall setup and make sure that attempted connections from the local machine aren't just silently dropped.  If on the other hand your delay is only in the server start-up, we would consider a PR that made that time configurable (probably preferred as a capybara setting rather than ENV variable), but you also should really look at whats happening during your apps startup - there are very few apps that should really take over a minute to startup in a test environment.
  As for the server spec, it is correct as written (an RSpec message expectation), Net::HTTP is expected to receive :start and when it does is mocked to raise an error

**Comment by tjouan** [comment]
Thank you for your fast and detailed answer,

On 2016-01-17 10:35:41 -0800, Thomas Walpole wrote:
> The monkey patch you have been using breaks the use of Capybara with multiple sessions, and is why you have test failures after applying it.  Capybara will sshare one server thread amongst multiple sessions that use the same application instance to reduce memory usage, etc.  Because of this the session first attempts to connect to an existing server instance (that may exist in another session - the first responsive? call) and if that connection is refused it then starts up a new server thread and waits (up to 60 seconds) until that is responsive.   

  What seemed odd to me in the server code and specs now makes perfect
sense, I understand how my change was "naive" and wrong regarding the
expected behavior you describe.


>   If you're having an issue where the first responsive? call takes a long time to be refused you really need to look at your system/firewall setup and make sure that attempted connections from the local machine aren't just silently dropped.

  The problem is I can't control this in all environments easily.
Forcing `localhost` instead of `127.0.0.1` (localhost does not always
resolve to this address) mitigates the issue in a few env where I can
temporary change system behavior but this is not very convenient or
wanted as I still generate false positive alerts due to first failed
connection attempt.


> If on the other hand your delay is only in the server start-up, we would consider a PR that made that time configurable (probably preferred as a capybara setting rather than ENV variable), but you also should really look at whats happening during your apps startup - there are very few apps that should really take over a minute to startup in a test environment.

  The server start-up is ok for me, I just needed to increase the
timeout during my diagnosis because it was shorter than the time
required for connect() to fail, in that case capybara would report
that server took to long to start, but in fact it will never be
started (need first connection failure).

  What I want to achieve seems specific, so I think the best path is
to maybe work on an alternative and independent implementation for the
server part, I'll give it a try when I can.

  Again, thank you a lot for taking the time to explain the behavior
of current server implementation in capybara.


> The "mailing list" is linked to right from the top of the README
> * Need help? Ask on the mailing list (please do not open an issue on GitHub): http://groups.google.com/group/ruby-capybara"

  I got a page in mixed language listing archives, but no address
listed or any doc. I found an unofficial process to "guess" it but
the mail I sent bounced back. I admit I didn't try very long, because
every time I try to use mailing lists on google-group I have
troubles :-)
