### ISSUE TITLE
Locator improvements

### ISSUE THREAD

**Issue by ain** [jnicklas/capybara#1640]
Currently, considering rather widely accepted front end conventions, e.g. BEM, the Capybara locator logic of `text, id, title or nested image's alt attribute` isn't catering the needs very well.

Scenario: only classes used in HTML with all content coming from CMS. 

I'd suggest finding a better way for the `locator` and/or also add support for class-based matching.

**Comment by twalpole** [comment]
Please read README.md and CONTRIBUTING.md 

1. Class based matching is a nightmare in most apps for the reason that classes are specifically designed for reuse on multiple elements which makes most queries ambiguous.  
2. The goal of Capybara is to emulate a user as much as possible, so it doesnt matter where the content for the page is coming from since we're dealing with the assembled displayed page.  In a test scenario that content is repeatable and therefore clicking on a button that says 'Submit Me' is what the user would be doing (id is there for cases where it's not possible to use visible text)
3.  Nothing is stopping you from using Capybara.add_selector to add your own selectors that use whatever locator strategy you want.
4.  Next time you post this kind of issue provide concrete examples to illustrate your point.
