### ISSUE TITLE
Race condition in open alerts with Selenium

### ISSUE THREAD

**Issue by jnicklas** [jnicklas/capybara#1670]
So this issue is totally my fault :( I'm experiencing an intermittent failure in an application where an alert appears just after a browser has reset the session, since it's in an unload handler. Here's how Capybara currently implements reset:

``` ruby
    def reset!
      if @touched
        driver.reset!
        assert_no_selector :xpath, "/html/body/*" if driver.browser_initialized?
        @touched = false
      end
      @server.wait_for_pending_requests if @server
      raise_server_error!
    end
```

In my case `assert_no_selector` is raising an unhandled alert error.

The reason `assert_no_selector` is called here in the first place is to make sure that resetting the session is synchronous. Instead of relying on the driver to make sure that it is, I thought that I could cheat and let Capybara handle this for the drivers. It seems that that was a mistake. That already became apparent in the need for the `browser_initialized?` hack. Of course we could handle this annoying case here as well, but there's no really way to rescue a Selenium-specific error here that isn't totally gross.

IMO we should cut out losses on this one and simply force the driver to make sure that restting is synchronous.

**Comment by jnicklas** [comment]
Stack trace: https://gist.github.com/jnicklas/f921d3e671547dc175c9f413c6da5426

**Comment by twalpole** [comment]
We can fix this in the selenium driver by checking for no elements in its reset! method, but removing the check from Session#reset! would be a breaking change

**Comment by twalpole** [comment]
@jnicklas Does the change in the selenium_driver_reset_synchronous branch fix your issue?

**Comment by twalpole** [comment]
@mhoran @route @jonleighton @jferris  Is reset! in your drivers currently synchronous, if not is it something that could be easily implemented?

**Comment by mhoran** [comment]
We don't do anything explicitly asynchronous in capybara-webkit on reset, and removing the `assert_no_selector` resulted in no failures. I'm in the process of porting capybara-webkit over to Chromium Embedded (CEF), as QtWebKit is dead. CEF is much more asynchronous than QtWebKit, and I've made every effort to wrap up asynchronous calls to be synchronous. However, there could be an issue here, and it's probably something I'll have to work around when the time comes.

**Comment by route** [comment]
@twalpole I believe that poltergeist works properly on this

**Comment by starsirius** [comment]
@mhoran Thanks for mentioning capybara-webkit is moving to use CEF. Just to report that we did run into the async session reset issue with capybara-webkit (sometimes session wasn't reset in time and leaked into the following spec). Adding back the single `assert_no_selector` line in capybara seems to solved it.

I am not sure if it's worth digging into the root cause at this point, but wonder if you have any insights. Thanks!

**Comment by twalpole** [comment]
@starsirius Do you happen to be using database_cleaner, and are triggering clean with an `after` block, rather than an 'append_after' block as database_cleaner recommends? - https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example

**Comment by starsirius** [comment]
@twalpole No. My app doesn't have a database so we don't use database_cleaner.

By the way, the temporary fix in my own [fork](https://github.com/starsirius/capybara/commit/c056ddb7979804d5ef4fdf31eca2621a9889886d) (capybara 2.7.1, because of capybara-webkit, + that single `assert_no_selector` line) seems to fix the issue. :(
