### ISSUE TITLE
have_css does not work for input attributes

### ISSUE THREAD

**Issue by Nghi93** [jnicklas/capybara#1682]
I am using rspec 3.4 and have updated capybara from 2.6.2 to 2.7 today.
After the update a few tests failed, e.g.: 
expect("<input value=\"published,unpublished\" class=\"hidden form-control\" type=\"hidden\" name=\"search[state]\" id=\"search_state\" />").to have_css('input[type="hidden"]') 

- works under 2.6.2

**Comment by twalpole** [comment]
Assuming you mean expect(page).... (rather than an empty string) this is as expected, the fact it worked in 2.6.2 with the rack-test driver was a bug. An input of type hidden is not visible on the page and is therefore not found by default.  Passing `visible: :all` as an option to find will make Capybara find invisible elements too
