### ISSUE TITLE
fill_in doesn not work because readonly: "false" is true

### ISSUE THREAD

**Issue by SanderMander** [jnicklas/capybara#1712]
After updating driver to marionette all fill_in methods stop working
Look at this string 
https://github.com/jnicklas/capybara/blob/master/lib/capybara/selenium/node.rb#L52
It is always true, because now self[:readonly] is equal "false" (for inputs tags) which is boolean true.

**Comment by twalpole** [comment]
Work to support marionette is underway in the marionette branch where this issue has already been fixed - marionette w/ selenium is not really ready for prime time yet - select/deselect of multiple selects doesn't work, multiple sessions don't work due to port conflicts, exexute_script can't access page defined functions, etc. you're better off sticking with FF 46 until 47.0.1 is released which should work with FirefoxDriver again

**Comment by twalpole** [comment]
See Issue #1709 and issue #1710
