### ISSUE TITLE
Request: Improve RSpec Response when asserting :count, :minimum, :maximum

### ISSUE THREAD

**Issue by tk8817** [jnicklas/capybara#1730]
Hi,

I have noticed that the RSpec matchers for asserting :count, :minimum, :maximum on an element return a purely boolean response but I imagine most folks would benefit from seeing what the found count was in relation to the expectation.

Current: 
```ruby
      expected #has_validation_errors?({:count=>1}) to return true, got false (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/global_steps.rb:22:in `/^exactly \((\d+)\) \[(\w+)\] \[(\w+)\](?:|s) should be visible$/'
      features/tests/repo/login.feature:36:in `Then exactly (1) [login_form] [validation_errors] should be visible'
```

Proposed:
```ruby
      expected: >= 1
           got:    0 (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/global_steps.rb:22:in `/^exactly \((\d+)\) \[(\w+)\] \[(\w+)\](?:|s) should be visible$/'
      features/tests/repo/login.feature:36:in `Then exactly (1) [login_form] [validation_errors] should be visible'
```

The proposed is based on what RSpec currently returns for its [Comparison Matchers](https://www.relishapp.com/rspec/rspec-expectations/v/3-5/docs/built-in-matchers/comparison-matchers)

Thoughts?

**Comment by twalpole** [comment]
Capybaras matchers do provide the counts - #<Capybara::ExpectationNotMet: expected to find css "h1, p" 5 times, found 4 matches: ... -, but has_validation_errors? isn't provided by Capybara, so I have no idea what matcher that actually is.

**Comment by twalpole** [comment]
From the error message I would guess you're calling something like

   expect(page.has_validation_messages?(count: 1)).to be true

If so that will never have a better error message, since you're calling a boolean method.  When using capybaras matchers you would do something like

    expect(page).to have_css('option', count: 5)

which would give the nice error message with count details, if on the other hand you did 

    expect(page.has_css?('option', count:5)).to be true  

you would not get the nice details because you're only using RSpecs built in comparison matcher which has no details about the count parameter.
