### ISSUE TITLE
attach_file should provide an option that doesn't check file existence

### ISSUE THREAD

**Issue by jinyulin** [jnicklas/capybara#1738]
If the test cases were executed on selenium grid, there is no need to check the file locally as all test will be executed on remote. I'd suggest to provide a new option 'check', then user can choose if check file existence or not before setting path.

**Comment by twalpole** [comment]
When using with selenium grid and attach_file you should be setting the file_detector in your driver settings - https://github.com/SeleniumHQ/selenium/blob/a81b559fe727c3ab4b5810bcc64da7182579c7a5/rb/lib/selenium/webdriver/common/driver_extensions/uploads_files.rb#L52 - so that the test files are kept with your tests and uploaded to the test instances as needed.  If you really don't want to do that and don't want file existence to be checked you can just find the file input and call #set on it directly

    find(:file_field, 'my file input').set(filename)
