### ISSUE TITLE
switching to database cleaner transaction strategy

### ISSUE THREAD

**Issue by mathieujobin** [jnicklas/capybara#1753]
my app has many tables, so the truncation strategy is taking longer and longer to execute. with close to 800 cucumber scenarios. that's a lot of DB cleaning happening in between. for often a few rows.

so I am told the transaction strategy should be much faster.

but most of my cucumber scenarios are tagged `@javascript` which spawn a different thread and so I am using a connection pool, hack that I found https://gist.github.com/mperham/3049152

Here is the patch to my application that I am using

https://gist.github.com/mathieujobin/024209d11f7613d969680b37c41ceeb4

But I am getting this error for every scenarios

`Mysql2::Error: SAVEPOINT active_record_1 does not exist: ROLLBACK TO SAVEPOINT active_record_1 (ActiveRecord::StatementInvalid)`

Although I have this option disabled as well

`Cucumber::Rails::World.use_transactional_fixtures = false`

any hints? anything Capybara could do to make this easier?

**Comment by twalpole** [comment]
Capybara specifically recommends using the truncation or deletion strategy when running JS tests due to the number of potential issues that trying to share a db connection can cause, and we can't provide help if you're choosing not to take that advice.  Additionally there is a potential issue of after_commit callbacks not being run when using transaction mode.   

In the future please ask howto questions on the mailing list as requested in the README

**Comment by mathieujobin** [comment]
thank you !
