### ISSUE TITLE
Selecting from dropdown should not leave dropdown open

### ISSUE THREAD

**Issue by phillipspc** [jnicklas/capybara#1761]
I have a test in which I select an option from a dropdown in a form, then click the submit button. I noticed this test was failing (intermittently, oddly enough) and when I dug deeper, I discovered the reason:

Selecting an option from a dropdown will cause that dropdown to remain open. This means that the following click does not actually submit the form, but merely serves to lose focus from the dropdown.

I was able to solve this in my test by explicitly blurring from the select: `page.execute_script("$('#my_select').blur()")` but I feel that this should not be necessary. Selecting with capybara should work as it does in real world usage, and close the dropdown after a selection is made.

**Comment by twalpole** [comment]
What driver are you using?

**Comment by phillipspc** [comment]
Hi @twalpole 
I'm using Selenium as the driver. The failing test code looks like this:
```
def test_should_create_the_scheduled_report_object
  user = FactoryGirl.create(:organization_owner, :with_full_permissions)
  sign_in_with_capybara user

  visit reports_new_path
  select "Week to Date", from: "period"

  choose "Schedule for email"
  select "Wednesday", from: "scheduled_report[day_of_week_to_send]"
  select "11:00", from: "scheduled_report[hour_of_day_to_send]"

  assert_difference "ScheduledReport.count", +1 do
    click_button "Schedule"
  end
end
```

and passes when I add `page.execute_script("$('#scheduled_report_hour_of_day_to_send').blur()")` before the assertion. Really nothing noteworthy about the HTML this tests...

There should be no conflicting listeners on the select. If this is not the standard/expected behavior from capybara (leaving the dropdown open), then I'll just live with this fix for now. I created this issue under the assumption that it was.

**Comment by twalpole** [comment]
@phillipspc That is definitely not the expected behavior since selecting the option clicks on the option it should behave just like with a user.  I'm actually a little surprised that your tests work at all since `click_button` occurs asynchronously (doesn't wait for the click to submit a request, etc) so I would expect assert_difference to routinely fail - unless you're doing something like sharing a database connection between the threads from a connection pool (mutex protected) which could then pause whichever thread doesn't get the connection first and would lead to intermittent failures.  Really your test should be something like the following to make sure the action has actually completed before checking for the updated count

    assert_difference "ScheduledReport.count", +1 do
      click_button "Schedule"
      # use any of Capybaras auto waiting assertions(assert_text, assert_selector, etc.) for 
      # whatever visible change occurs on the page when the schedule has been crated
      assert_text "New schedule created"
    end

**Comment by twalpole** [comment]
@phillipspc Also, what browser are you using with Selenium?

**Comment by phillipspc** [comment]
@twalpole using firefox with selenium

**Comment by twalpole** [comment]
@phillipspc Without a reproducible example I don't think there's much we can do here. We have a number of tests -  like https://github.com/jnicklas/capybara/blob/master/lib/capybara/spec/session/select_spec.rb#L43 - that are run against selenium w/firefox (and chrome) which select items and then click buttons and they pass every time.

**Comment by phillipspc** [comment]
@twalpole thats fine. thanks for taking a look. We're also on an older version, so that may be a factor.
