### ISSUE TITLE
prefer_exact matches string as a substring in matching elements (eg 23, 30, 3 for exact match of 3)

### ISSUE THREAD

**Issue by om-nishu-trantor** [jnicklas/capybara#1768]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 2.7.1

Driver Information (and browser if relevant): selenium-webdriver 2.53.4

## Expected Behavior
mtch = find_all('#my_calendar td.day', text: '3', match: :prefer_exact)
mtch.count == 1
mtch.first.text == '3'
## Actual Behavior
mtch = find_all('#my_calendar td.day', text: '3', match: :prefer_exact)
mtch.count == 7
mtch.first.text == '30'
mtch.second.text == '23'
mtch.third.text == '3'
## Steps to reproduce
Use above mentioned script to find an element, make sure that you have your matching string as a substring in same xpath but at different location.

**Comment by twalpole** [comment]
:prefer_exact affects the behavior of finders through the :exact option, which as explained [here](https://github.com/jnicklas/capybara#exactness) only affects XPath#is expressions (which are used in most of Capybaras built-in specialized selectors when looking for things like label contents).  It does not affect the :text option which can be passed to finders.  match :prefer_exact also doesn't have any effect on find_all/all queries since by using #all you're implying you want more than one result.  Where prefer_exact would make a difference would be in something like

    fill_in('Password', with: 'password', match: :prefer_exact)

This uses the :fillable_field selector which will look at the label content of elements to find the desired element.  It will match an element with text of 'Password' if it exists, and if not it would match 'Your Password Here'.

If you do want exact matching for the :text option you need to pass a regex

    mtch = find_all('#my_calendar td.day', text: /^3$/)

**Comment by om-nishu-trantor** [comment]
:+1:  It works.
