### ISSUE TITLE
each.with_index on Capybara::Result throws NoMethodError

### ISSUE THREAD

**Issue by dvandersluis** [jnicklas/capybara#1777]
## Meta
Capybara Version:
2.10.1
Driver Information (and browser if relevant):
Poltergeist 1.11.0 / PhantomJS 2.1.1

## Steps to reproduce
On a page with multiple checkbox `<input>` tags:

```rb
all('input[type=checkbox]').each.with_index do |ch, idx|
  break if idx == count
  check ch[:id]
end
```

## Expected Behavior
Check first `count` checkboxes.

## Actual Behavior

```
NoMethodError: undefined method `call' for nil:NilClass
Did you mean?  caller
/Users/daniel/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/result.rb:47:in `block in each'
/Users/daniel/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/result.rb:44:in `loop'
/Users/daniel/.rvm/gems/ruby-2.3.1/gems/capybara-2.10.1/lib/capybara/result.rb:44:in `each'
/Users/daniel/RubymineProjects/myproject/features/step_definitions/my_steps.rb:53:in `block (2 levels) in <top (required)>'
```

FYI - Changing `each.with_index` to `each_with_index` works.

**Comment by twalpole** [comment]
`#all` returns a Capybara::Result not an Array - if you want accces to all the methods on an array you can call `#to_a` on it.

    all('input[type=checkbox]').to_a.each.with_index do |ch, idx|

**Comment by twalpole** [comment]
Actually, thinking about this -- the only reason it doesn't work is because the #each implemented in Capybara::Result doesn't return an enumerator when called without a block.  I'm going to implement that, but for future info  Capybara::Result is not guaranteed to behave exactly like an Array but can be converted to an array as shown above if necessary.

**Comment by twalpole** [comment]
Fixed via 4bd9806804c71e939188e720e8bb10fcb8cf9530

**Comment by dvandersluis** [comment]
Thanks!

**Comment by twalpole** [comment]
@dvandersluis You're welcome, thanks for pointing this out.  On a side note, rather than `all('input[type=checkbox]')` Capybara does provide a [:checkbox selector](https://github.com/jnicklas/capybara/blob/master/lib/capybara/selector.rb#L298) , so you could just do `all(:checkbox)`  which also supports a number of filter options too
