### ISSUE TITLE
find_field method doesn't find field by label if data-reactid used

### ISSUE THREAD

**Issue by ievgenChernikov** [jnicklas/capybara#1780]
## Meta
Capybara Version:
2.7.1
Driver Information (and browser if relevant):
selenium-webdriver (2.51.0) with Firefox 46.0

## Steps to reproduce
Use `find_field('Name')` on the following html:
```
<label data-reactid="123.123.$123.1">Name</label>
<input type="text" name="menu-name" value="Main menu" data-reactid="123.123.$123.1">
```

## Expected Behavior
Element should be found as ` find_field` method looks at `label` according to documentation.

## Actual Behavior
If I use method `find_field('Name')` on this html it doesn't find field.

`Capybara::ElementNotFound: Unable to find field "Name"
`

**Comment by twalpole** [comment]
This is because Capybara follows the HTML spec and doesn't know anything about react.  The HTML spec states that labels are linked to inputs either by wrapping them or with a `for` attribute equal to the `id` attribute of the input.

It's easy enough to add data-reactid label linking to the field selector if you want it in your own project - something like

    module CapybaraReactid
      def locate_field(xpath, locator, options={})
         super + xpath[XPath.attr(:'data-reactid').equals(XPath.anywhere(:label)[XPath.string.n.is(locator)].attr(:'data-reactid'))]
      end
    end

    Capybara::Selector.prepend CapybaraReactid

should work
